### ISSUE TITLE
Scrollbars are never visible in screenshots

### ISSUE THREAD

**Issue by tenox7** [chromedp/chromedp#979]
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.7.6
$ google-chrome --version
Google Chrome 96.0.4664.93
$ go version
go version go1.17.3 darwin/amd64
```

#### What did you do? Include clear steps.

```go
chromedp.Flag("hide-scrollbars", false),
...
chromedp.Run(ctx,
  emulation.SetDeviceMetricsOverride(1024, 768, 1.0, false),
  chromedp.Navigate("http://www.cnn.com/"),
  chromedp.Sleep(time.Second*5),
  chromedp.FullScreenshot(&buf, 100),
)
```

Also same if I use:

```
chromedp.CaptureScreenshot(&buf),
```

#### What did you expect to see?
A screenshot WITH scrollbars. This used to work fine before.

#### What did you see instead?
Screenshot WITHOUT scrollbars.

With or without the `hide-scrollbars` flag, with or without `headless`, with or without `emulation.SetDeviceMetricsOverride`, with `FullScreenshot` or with `CaptureScreenshot`. Scrollbars are never shows in a screenshot. While running in headed mode I see the scrollbars. They are just not included in a screenshot (screenshot size is smaller / cropped just before scrollbars).

**Comment by ZekeLu** [comment]
> This used to work fine before.

Can you provide more Information (the version of the browser and `chromedp`)?

**Comment by tenox7** [comment]
I have checked and it doesn't matter what version of Chrome browser. I'm using `Google Chrome 96.0.4664.93`.

Everything works correctly with this:

```
	github.com/chromedp/cdproto v0.0.0-20210305224431-50b9f457e822
	github.com/chromedp/chromedp v0.6.8
```

With this, no scrollbars:

```
	github.com/chromedp/cdproto v0.0.0-20211205231339-d2673e93eee4
	github.com/chromedp/chromedp v0.7.6
```

**Comment by ZekeLu** [comment]
@tenox7 Thanks for the information. The breaking change is introduced by this commit: 06a9527f.

If you want the scrollbar, I'm afraid that you have to implement the function yourself. For example, to capture the screenshot of the viewport with scrollbar:

```go
func CaptureScreenshotWithScrollbar(res *[]byte) chromedp.Action {
	if res == nil {
		panic("res cannot be nil")
	}

	return chromedp.ActionFunc(func(ctx context.Context) error {
		var err error
		*res, err = page.CaptureScreenshot().
			// comment out the next line to show scrollbar.
			// WithCaptureBeyondViewport(true).
			Do(ctx)
		return err
	})
}
```

**Comment by ZekeLu** [comment]
I think the issue has been addressed. Closing.

**Comment by tenox7** [comment]
@ZekeLu I'd like to re-open the issue. This is unfortunately not working.

I have tried your example, but scrollbars are not captured in the screenshot.

In fact `WithCaptureBeyondViewport(true)` is included by default in `CaptureScreenshot()` here:
https://github.com/chromedp/chromedp/blob/19b37c1b76b6a16d165e69e18756475ddc8f6432/screenshot.go#L91

...but it still doesn't work. Thank you!
